const defaultQuestions = {

  /* =========================
     BESZÉLGETŐS TÉMÁK
  ==========================*/
  temak: {

    kapcsolodas: ["Mikor érezted először, hogy komoly lehet köztünk?",
"Mi volt az a pillanat, amikor belém szerettél?",
"Mi fogott meg bennem legelőször?",
"Mikor voltál a legbüszkébb ránk?",
"Mi az a tulajdonságom, amit titkon irigyelsz?",
"Mi az, amit csak én tudok belőled előhozni?",
"Melyik közös emlékünk a „mi történetünk” kezdete?",
"Mikor érezted, hogy igazán egy csapat vagyunk?",
"Mi az a mondatom, ami mélyen benned maradt?",
"Mikor hiányzom a legjobban?",
"Mi az, amitől különlegesnek érzed magad mellettem?",
"Ha most kellene újra randira hívnod, mit mondanál?",
"Melyik közös nevetésünket nem felejted el soha?",
"Mi az, amit szerinted csak mi értünk igazán egymásban?",
"Mikor érezted magad a legbiztonságosabban velem?",
"Mi az a kis szokásom, amit imádsz?",
"Mi az a pillanat, amikor majdnem elsírtad magad miattam?",
"Mikor volt a legmeghittebb beszélgetésünk?",
"Mi az, amit mások nem látnak, de köztünk nagyon erős?",
"Ha egy szóval kellene leírnod minket, mi lenne az?",
"Melyik randink volt a legemlékezetesebb?",
"Mi az a gesztusom, amit sosem felejtesz el?",
"Mikor érezted, hogy teljesen önmagad lehetsz mellettem?",
"Mi az, amitől szerinted működik köztünk a dolog?",
"Mi volt az első dolog, amit megszerettél bennem?",
"Mikor érezted, hogy fontos vagyok neked?",
"Mi az, amit a kapcsolatunk tanított neked?",
"Melyik közös kihívás tett minket erősebbé?",
"Mi az a pillantásom vagy érintésem, ami megnyugtat?",
"Ha újra kezdhetnénk, min nem változtatnál?",
"Mi az a közös cél, amitől izgatott leszel?",
"Mikor volt az a pont, amikor tudtad: „ő kell nekem”?",
"Mi az, amit szerinted jobban csinálunk, mint a legtöbb pár?",
"Mi az, amit tőlem tanultál meg magadról?",
"Melyik közös fotónk mesél rólunk a legtöbbet?",
"Mi az, amit legjobban szeretsz bennem, amikor nehéz napod van?",
"Mikor érezted a legerősebb összhangot köztünk?",
"Mi az, amit sosem szeretnél elveszíteni a kapcsolatunkból?",
"Miben egészítjük ki egymást a legjobban?",
"Mi az, amitől úgy érzed, hazataláltál mellettem?",
"Ha egy dal lenne a kapcsolatunk, milyen hangulatú lenne?",
"Mi az a közös élmény, ami örökre összeköt minket?",
"Mikor érezted a legerősebb kötődést hozzám?",
"Mi az, amit szerinted még sokáig együtt fogunk csinálni?",
"Mi az a tulajdonságom, ami a leginkább megnyugtat?",
"Mikor voltál a legboldogabb velem?",
"Mi az, amit a kapcsolatunkban a legértékesebbnek tartasz?",
"Mi az a mondat, amit most szívesen hallanál tőlem?",
"Ha most visszanézel ránk, mire vagy a leghálásabb?",
"Mi az, ami miatt ma is engem választanál?"
],

    mennyireIsmersz: ["Mi az az étel, amit sosem rendelne étteremben?",
"Mi az első dolog, amit csinál, amikor hazaér?",
"Mi az a dolog, amitől a legjobban stresszel?",
"Melyik tulajdonságára a legbüszkébb?",
"Mi az a napszak, amikor a legjobb kedve van?",
"Mi az a dolog, amit mindig halogat?",
"Mi az a szokása, amit próbált már elhagyni?",
"Mi az a hely, ahol a legnyugodtabb?",
"Mi az, amitől azonnal mosolyogni kezd?",
"Mi az a témakör, amiről órákig tud beszélni?",
"Mi az a tulajdonság, amit mások gyakran félreértenek benne?",
"Mi az a dolog, amitől igazán motivált lesz?",
"Mi az a mondat, amit tőled a legszívesebben hall?",
"Mi az a gesztus, amitől rögtön ellágyul?",
"Mi az a gyerekkori élmény, ami formálta őt?",
"Mi az a döntés, amit ha lehetne, újragondolna?",
"Mi az a dolog, amit sosem kérne, de jól esne neki?",
"Mi az a helyzet, amikor a legmagabiztosabb?",
"Mi az, amitől igazán sebezhetőnek érzi magát?",
"Mi az a szituáció, amikor inkább visszahúzódik?",
"Mi az a bók, amit nehezen fogad el?",
"Mi az a dolog, amit mindig túlkomplikál?",
"Mi az a tulajdonságod, amit titokban imád?",
"Mi az a tulajdonságod, amitől néha megőrül?",
"Mi az a hely, ahol a legszívesebben csókolnálak meg?",
"Mi az az érintés, amitől megborzong?",
"Mi az a szituáció, ami azonnal beindítja?",
"Inkább lassú felvezetést szeret, vagy hirtelen intenzitást?",
"Mi az a rész rajtad, amit a legvonzóbbnak talál?",
"Mi az a pillanat, amikor a legszexibbnek lát téged?",
"Mi az a dolog, amitől elveszíti a kontrollt?",
"Mi az a titkos fantázia, amit valószínűleg élvezne?",
"Mi az a szó vagy mondat, amitől felhevül?",
"Mi az a határ, amit csak teljes bizalommal lépne át?",
"Mi az a közös élmény, amit még mindenképp át akar élni?",
"Mi az a kaland, amitől izgatott lenne?",
"Mi az a félelem, amit nem mindig mutat ki?",
"Mi az a dolog, amit leginkább tisztel benned?",
"Mi az a szokásod, amitől biztonságban érzi magát?",
"Mi az a helyzet, amikor a leginkább vágyik rád?",
"Mi az a nap, ami szerinte fordulópont volt a kapcsolatotokban?",
"Mi az a közös vicc, amit csak ti értetek?",
"Mi az a tulajdonsága, amit te talán alábecsülsz?",
"Mi az a jövőbeli terv, amit komolyan elképzel veled?",
"Mi az a hely, ahol titokban kipróbálna valami merészet?",
"Mi az a szerep, amit szívesen felvenne egy játékban?",
"Inkább irányítani szeret, vagy átadni az irányítást?",
"Mi az a helyzet, amikor teljesen ellazul melletted?",
"Mi az a részlet rajtad, amit mindig észrevesz?",
"Mi az a dolog, amit rólad mindig megjegyez?",
"Mi az a mozdulatod, amit különösen szeret?",
"Mi az a közös cél, ami igazán izgatja?",
"Mi az a titok, amit szerinted még nem mondott el teljesen?",
"Mi az az egy dolog, amiben biztos, hogy ismered… vagy mégsem?",
"Mikor érzi magát a leginkább szeretve?",
"Mit szeretne leginkább hallani egy vita után?",
"Mi az, amitől a legkönnyebben beindul?",
"Inkább kezdeményez, vagy ha kezdeményeznek nála?",
"Mi az a zene, amit titokban szeret?",
"Mi az a szokása, amit kevesen tudnak róla?",
"Mi az a hely, ahová bármikor szívesen visszamenne?",
"Mi az a tulajdonság másokban, amit nehezen visel?",
"Mi az a gyerekkori álma, ami még mindig él benne?",
"Mi az a mondat, amit gyakran ismétel?",
"Mi az, amitől azonnal jobb kedve lesz?",
"Mi az a bók, ami igazán betalál nála?",
"Mitől érzi magát igazán vonzónak?",
"Mi az a ruhadarab rajtad, amit a legjobban szeret?",
"Mi az a közös emlék, amit gyakran felhoz?",
"Mi az, amit sosem vallana be elsőre?",
"Mi az a film vagy sorozat, amit újra tudna nézni?",
"Mi az a tulajdonságod, amit a legjobban szeret?",
"Mi az, amitől igazán kiborul?",
"Mi az a cél, amit mostanában komolyan gondol?",
"Mi az a félelem, amit ritkán mutat ki?",
"Mit csinál, amikor igazán fáradt?",
"Mi az a dolog, amit szerinted alábecsül magában?",
"Mi az a közös szokásotok, amit imád?",
"Mikor érzi magát a legszexibbnek?",
"Mi az az érintés, amit a legjobban szeret?",
"Mi az a helyzet, amikor teljesen önmaga?",
"Mi az a tulajdonság, amit titokban szeretne fejleszteni?",
"Mi az a dolog, amit rólad irigyel?",
"Mi az a gesztus, amitől elolvad?",
"Mi az a helyszín, ahol titokban szívesen lenne veled?",
"Mi az a dolog, amit sosem próbált még, de gondolt rá?",
"Mi az a szó, ami legjobban leírja őt?",
"Mi az, amitől biztonságban érzi magát?",
"Mi az a pillanat, amikor a legvonzóbb vagy számára?",
"Mi az a helyzet, amikor ő szeret dominálni?",
"Mi az a dolog, amit gyerekkéntől mostanáig nem változtatott meg?",
"Mi az a döntés, amire a legbüszkébb?",
"Mi az a bók, amit még sosem hallott, de jól esne neki?",
"Mi az a szituáció, amitől zavarba jön?",
"Mi az a fantázia, amit valószínűleg kipróbálna?",
"Mi az a határ, amit biztosan nem lépne át?",
"Mi az a titkos vágya, amit ritkán mond ki?",
"Mi az a közös élmény, amit még meg szeretne élni veled?",
"Mi az, amit a legjobban értékel benned?",
"Mi az az apró részlet, amit mindig észrevesz rajtad?"
],

    melyseg: ["Mitől félsz a legjobban egy kapcsolatban?",
"Mi az, amit nehezen mutatsz ki mások előtt?",
"Mikor érzed magad igazán sebezhetőnek?",
"Mi az az érzés, amit gyakran elfojtasz?",
"Mi az, amit gyerekkorodból még mindig hordozol?",
"Mi az a belső bizonytalanság, amit ritkán mondasz ki?",
"Mikor érzed magad a legerősebbnek?",
"Mi az a dolog, amitől titokban tartasz?",
"Mi az a múltbeli élmény, ami formálta a szeretetről alkotott képed?",
"Mi az a tulajdonságod, amit nehéz elfogadnod magadban?",
"Mikor sírtál utoljára, és miért?",
"Mi az, amitől igazán büszke vagy magadra?",
"Mi az, amit még nem dolgoztál fel teljesen?",
"Mi az a gondolat, ami néha visszatér benned?",
"Mi az, amit a legnehezebb bevallani magadnak?",
"Mikor érzed magad elveszettnek?",
"Mi az, amit leginkább szeretnél, hogy megértsek benned?",
"Mi az a belső harc, amit kevesen látnak?",
"Mi az, amitől igazán megnyugszol?",
"Mi az az érzés, amit mellettem könnyebben megélsz?",

"Amikor vitázunk, mire lenne a legnagyobb szükséged?",
"Mi az, amit szerinted félreértek benned?",
"Hogyan reagálsz, amikor megbántva érzed magad?",
"Mi az a mondat, amit sosem szeretnél hallani tőlem?",
"Inkább azonnal megbeszéled a problémát, vagy idő kell?",
"Mi az, amitől bezárkózol?",
"Mi az, amit gyakran visszatartasz egy vita során?",
"Mi az a konfliktusmintád, amit magaddal hoztál?",
"Mikor érzed azt, hogy nem figyelek rád eléggé?",
"Mi az a viselkedésem, ami bánt, de ritkán mondod?",
"Mi az, amit egy vita után leginkább szeretnél tőlem?",
"Mi az a szó, ami nálad azonnal falat húz?",
"Hogyan mutatod ki, ha csalódott vagy?",
"Mi az a téma, amit nehéz felhoznod?",
"Mikor érzed azt, hogy nem értjük egymást?",
"Mi segít a legjobban kiengesztelni?",
"Mi az, amit konfliktus közben magadban mondasz?",
"Mi az, amit másképp szeretnél csinálni vitákban?",
"Mikor érzed igazán, hogy meghallgatlak?",
"Mi az a mondat, amitől újra biztonságban érzed magad?",

"Hol látod magad 5 év múlva, és ott én hol vagyok?",
"Mi az a közös cél, amit komolyan gondolsz velem?",
"Mi az, amit mindenképp szeretnél még együtt megélni?",
"Mi az a döntés, amitől félsz, de tudod, hogy egyszer meg kell hozni?",
"Mit jelent számodra az elköteleződés?",
"Mi az, amit a jövőnkkel kapcsolatban izgatottan vársz?",
"Mi az, amitől tartasz a közös jövőben?",
"Milyen életstílust képzelsz el magadnak hosszú távon?",
"Mi az a közös álom, amit nem adnál fel?",
"Mit jelent számodra a stabilitás?",
"Mi az, amit anyagilag vagy egzisztenciálisan fontosnak tartasz?",
"Hol szeretnél élni hosszú távon?",
"Mit jelent számodra a család?",
"Milyen közös hagyományt alakítanál ki velünk?",
"Mi az a kompromisszum, amit nehezen hoznál meg?",
"Mi az, amit biztosan nem adnál fel egy kapcsolatért?",
"Milyen jövőt látsz magad előtt, ha minden jól alakul?",
"Mi az, amitől biztonságosnak érzed a közös jövőt?",
"Mi az a közös projekt, amit szívesen megvalósítanál?",
"Milyen példát szeretnél mutatni együtt?",

"Volt már olyan pillanat, amikor megkérdőjelezted a kapcsolatunkat?",
"Mi az, amitől félsz bennem?",
"Mi az a részem, amit nehezen fogadsz el?",
"Mi az, amit ha elveszítenél bennem, nagyon fájna?",
"Volt olyan, amit nem mondtál ki, hogy ne bánts?",
"Mi az a téma, amit kerülni szoktál velem?",
"Mikor érzed azt, hogy nem adsz eleget?",
"Mi az, amit szerinted változtatnom kellene?",
"Mi az, amit te szeretnél fejleszteni magadon miattunk?",
"Mi az a dolog, amitől tartasz, ha teljesen őszinték lennénk?",

"Mi az a minta, amit nem szeretnél továbbvinni?",
"Mi az, amit a legjobban szégyellsz magaddal kapcsolatban?",
"Mi az, amit titokban remélsz tőlem?",
"Mikor érzed, hogy igazán látlak téged?",
"Mi az a fájdalom, amit még nem engedtél el?",
"Mi az, amit szeretnél, hogy egyszer teljesen megértsek benned?",
"Mi az a belső határ, amit nehéz kimondani?",
"Mikor érzed azt, hogy igazán egy oldalon állunk?",
"Mi az, amitől igazán félsz elveszíteni?",
"Ha most teljesen őszinte lennél, mit mondanál?"
],

    intimitas: ["Mitől érzed magad igazán közel hozzám?",
"Mi az a gesztus, amitől biztonságban érzed magad mellettem?",
"Hogyan szereted, ha kimutatom a szeretetem?",
"Mitől érzed magad igazán fontosnak számomra?",
"Mikor érzed a legerősebb kötődést közöttünk?",
"Mi az, amit gyakrabban szeretnél hallani tőlem?",
"Hogyan tudlak a legjobban támogatni érzelmileg?",
"Mi az, amitől igazán megnyílsz?",
"Milyen helyzetben érzed, hogy teljesen egy oldalon állunk?",
"Mi az, ami segít abban, hogy jobban megértsük egymást?",

"Mire van most a legnagyobb szükséged tőlem?",
"Mi az, amitől erősebbnek érzed a kapcsolatunkat?",
"Milyen közös szokást alakítanál ki velünk?",
"Mi az a figyelmesség, amitől különlegesnek érzed magad?",
"Milyen formában szeretsz leginkább kapcsolódni?",
"Mi az, amit gyakrabban csinálhatnánk együtt?",
"Mi az a minőségi idő, ami számodra igazán számít?",
"Mitől érzed azt, hogy tényleg figyelek rád?",
"Mi az a dolog, amit ha rendszeresen megkapnál, boldogabb lennél?",
"Hogyan tudnánk még tudatosabban építeni a kapcsolatunkat?",

"Milyen érintéstől lazulsz el a legjobban?",
"Mikor esik a legjobban az ölelésem?",
"Hogyan szeretsz közeledni hozzám?",
"Mi az a pillanat, amikor leginkább vágysz a közelségemre?",
"Milyen apró testi jelzés esik a legjobban?",
"Mikor érzed magad a legkívánatosabbnak mellettem?",
"Mi az, amitől igazán meghitt lesz egy pillanat?",
"Hogyan szeretsz megnyugodni a karjaim között?",
"Mi az a helyzet, amikor különösen jólesik az érintésem?",
"Hogyan tudnám még jobban éreztetni veled, hogy kívánlak?",

"Milyen közös élményt szeretnél, ami még közelebb hozna minket?",
"Hogyan képzeled el a kapcsolatunk érzelmi fejlődését?",
"Mi az a közös cél, ami még inkább összekötne?",
"Milyen hagyományt alakítanál ki velünk?",
"Hogyan tudnánk még több bizalmat építeni?",
"Mit szeretnél, hogy soha ne veszítsünk el egymásban?",
"Milyen jövőbeli pillanatot vársz a legjobban?",
"Mi az a közös szokás, amit hosszú távon is megőriznél?",
"Mit jelent számodra a hosszú távú érzelmi biztonság?",
"Hogyan tudnánk még tudatosabban jelen lenni egymás számára?",

"Mi az, amit mellettem tanultál meg a szeretetről?",
"Mitől érzed, hogy igazán látnak és elfogadnak?",
"Hogyan tudlak segíteni abban, hogy még jobban önmagad lehess?",
"Mi az a vágyad, amit szeretnél, ha jobban értenék?",
"Mi az, amit szeretnél még mélyebben megélni velem?",
"Hogyan tudjuk jobban kifejezni egymás felé a hálánkat?",
"Mi az, ami a legjobban megerősíti benned, hogy jó helyen vagy?",
"Mitől érzed, hogy valódi társak vagyunk?",
"Mi az a belső igényed, amit szeretnél, ha figyelembe vennék?",
"Hogyan szeretnéd, hogy a kapcsolatunk érzelmileg fejlődjön a következő évben?"
],

    szexualitas: ["Hogyan szereted, ha kezdeményezek nálad?",
"Mitől érzed magad igazán kívánatosnak?",
"Milyen tempóban esik a legjobban az intimitás?",
"Mi az a visszajelzés, amit szívesen hallasz közben?",
"Inkább gyengéd vagy intenzív közeledés indít be?",
"Mi az, amitől teljesen el tudod engedni magad?",
"Hogyan jelzed, ha vágysz rám?",
"Mi az a dolog, amit gyakrabban szeretnél tőlem?",
"Milyen érintésből nem lehet elég?",
"Inkább hosszú felvezetést szeretsz, vagy gyors egymásra találást?",
"Mikor kívánsz a leginkább?",
"Mi az, amitől magabiztosnak érzed magad az ágyban?",
"Mi az a mozdulat, amit különösen szeretsz bennem?",
"Hogyan szereted, ha reagálok rád?",
"Milyen hangulat hoz igazán lázba?",
"Mi az a szituáció, amitől azonnal megváltozik a levegő köztünk?",
"Inkább te vezetsz, vagy szereted, ha vezetnek?",
"Mi az a kis részlet, ami nálad sokat számít?",
"Mitől érzed igazán figyelmesnek a másikat?",
"Mi az, amit szerinted még jobban csinálhatnánk?",
"Mi az a vágyad, amit ritkán mondasz ki?",
"Mi az a helyzet, amikor könnyen elveszíted a kontrollt?",
"Inkább szemkontaktus vagy suttogás indít be jobban?",
"Milyen környezet fokozza leginkább a vágyat benned?",
"Mi az a mondat, amitől megborzongsz?",
"Hogyan szereted, ha felfedezlek?",
"Mi az, amitől teljesen jelen tudsz lenni?",
"Inkább kiszámítható vagy meglepő fordulatok?",
"Milyen ritmusban esik a legjobban?",
"Mi az a visszajelzés, amitől még inkább megnyílsz?",
"Mi az, amit szeretnél, ha bátrabban kérnék tőled?",
"Milyen szerepben érzed magad a legizgalmasabbnak?",
"Mi az a dolog, amitől megnő benned a feszültség?",
"Inkább lassan felépített vágy vagy hirtelen fellobbanó szenvedély?",
"Mi az, amitől biztonságban mersz merészebb lenni?",
"Mi az a jel, ami nálad egyértelmű vágyjelzés?",
"Hogyan szereted, ha reagálok a tested jelzéseire?",
"Mi az a dolog, amit szeretnél, ha jobban figyelnék rajtad?",
"Mi az, ami számodra igazán érzéki?",
"Mi az, amitől elolvad benned az ellenállás?",

"Melyik testrészed a legérzékenyebb?",
"Hol szereted a legjobban, ha megérintelek?",
"Mi az a mozdulat, amitől azonnal reagálsz?",
"Inkább erőteljesebb vagy finomabb érintéseket szeretsz?",
"Milyen csók indít be leginkább?",
"Mi az, amitől felgyorsul a légzésed?",
"Milyen testkontaktus esik a legjobban közben?",
"Mi az a tempó, amitől igazán beindulsz?",
"Milyen hangok vagy reakciók hatnak rád a legjobban?",
"Mi az a konkrét dolog, amit szeretnél, ha többször csinálnék?",
"Inkább lassan felfedező vagy szenvedélyesen intenzív?",
"Mi az, amitől igazán elveszíted a kontrollt?",
"Melyik pozícióban érzed magad a legmagabiztosabbnak?",
"Mi az a gesztus, amitől dominánsnak érzed magad?",
"Mi az, amitől inkább átadnád az irányítást?",
"Milyen ritmusban esik a legjobban a mozgás?",
"Mi az, amitől teljesen ellazul a tested?",
"Mi az a rész rajtam, amit a legizgatóbbnak találsz?",
"Mi az, amitől leginkább kívánsz még többet?",
"Mi az a konkrét élmény, amit szívesen ismételnél?",

"Ha egy titkos helyszínt választhatnál kettőnknek, hol lenne?",
"Milyen szerepjáték izgatná leginkább a fantáziád?",
"Inkább tiltott vagy luxus hangulat hoz lázba?",
"Ha egy estére új szerepet kapnál, ki lennél?",
"Mi az a fantázia, amit biztonságban megosztanál velem?",
"Milyen környezet fokozná legjobban a feszültséget?",
"Ha meglephetnélek egy merész helyzettel, mi legyen az?",
"Inkább váratlan helyszín vagy tudatosan megtervezett jelenet?",
"Milyen öltözet hozná ki belőled a legtöbbet?",
"Ha nem lennének gátlások, mi lenne az első lépésed?",
"Milyen szituációban adnád át teljesen az irányítást?",
"Mi az a jelenet, amit gyakran elképzelsz?",
"Inkább sötét, titokzatos hangulat vagy fényben megélt intenzitás?",
"Ha csak a fantáziád vezetne, milyen lenne az este forgatókönyve?",
"Milyen váratlan fordulat izgatna fel leginkább?",
"Milyen szerepet osztanál rám egy merész játékban?",
"Mi az a helyzet, amit eddig csak elképzeltél?",
"Inkább lassú, érzéki felvezetés egy különleges helyen, vagy hirtelen szenvedély?",
"Ha egy titkos kívánságod teljesülne, mi lenne az?",
"Mi az a közös fantázia, amit egyszer mindenképp megélnél?",

"Hol szereted a legjobban, ha megcsókollak?",
"Milyen csók az, amitől azonnal megváltozik benned a hangulat?",
"Melyik a kedvenc pózod, és miért pont az?",
"Inkább lassú, mély csókok vagy szenvedélyes, intenzívek indítanak be jobban?",
"Amikor a szemedbe nézek közben, mit érzel?",
"Mennyire fontos számodra a szemkontaktus intimitás közben?",
"Szeretsz inkább adni vagy kapni az orális kényeztetésben?",
"Mi az, amit különösen szeretsz orálisan?",
"Mi az a reakció tőlem, amitől még jobban élvezed?",
"Inkább gyengéd vagy határozott érintés esik jobban az érzékeny pontokon?",
"Hol érzed magad a legérzékenyebbnek a testeden?",
"Melyik mozdulatom indít be a legjobban?",
"Inkább irányítasz, amikor igazán beindulsz, vagy átadod magad?",
"Milyen tempóban szeretsz haladni, amikor igazán élvezed?",
"Mi az a testhelyzet, amiben a legkívánatosabbnak érzed magad?",
"Mi az, amitől igazán intenzívvé válik számodra az élmény?",
"Szereted, ha közben beszélünk, vagy inkább a hangok számítanak?",
"Mi az a rész rajtam, amit a legszívesebben csókolsz?",
"Mi az, amitől a leginkább elveszíted az időérzéked?",
"Mi az a konkrét dolog, amit szeretnél, ha bátrabban kérnék tőled?"
]

  },

  /* =========================
     KIHÍVÁS – 5 SZINT
  ==========================*/
  kihivas: {
    level1: [
  "Húzd magadhoz a derekánál, és csókold meg lassan.",
  "Csókolj végig a nyakán 30 másodpercig.",
  "Simíts végig a hátán két kézzel, lassan lefelé.",
  "Táncoljatok szorosan 1 percig beszéd nélkül.",
  "Harapj finoman az alsó ajkába csók közben.",
  "Simíts végig a combján ruhán keresztül.",
  "Csókolj meg három különböző helyen a testén.",
  "Öleld át hátulról, és csókolj a vállába.",
  "Húzd végig az ujjaid az oldalán felfelé.",
  "Nézz a szemébe, majd csókold meg hirtelen.",
  "Csókolj végig a kulcscsontjától az álláig.",
  "Táncoljatok lassú zenére, csípőtök összeérjen.",
  "Simíts végig a csípőjén, és húzd közelebb.",
  "Csókolj végig egy teljes percig megszakítás nélkül.",
  "Vezesd a kezét a mellkasodra.",
  "Csókolj a füléhez közel, majd a nyakára.",
  "Fogd meg a kezét, és húzd a derekadra.",
  "Simíts végig a hajában, majd csókold meg mélyen.",
  "Érintsd meg a combja belső oldalát finoman.",
  "Fordítsd meg, és csókold meg hátulról a nyakát.",
  "Csókolj végig az állkapcsán lassan.",
  "Húzd közelebb a csípőjénél, és tartsd ott.",
  "Simíts végig a karján az ujjaitól a válláig.",
  "Érintsd meg a derekát két kézzel, és csókold meg szenvedélyesen.",
  "Táncoljatok úgy, hogy a kezed végig a csípőjén marad.",
  "Csókolj végig a mellkasán ruhán keresztül.",
  "Húzd végig az ajkadon az ujjad, miközben nézed.",
  "Simíts végig a hátán lefelé, majd vissza.",
  "Tartsd a tekintetét csók közben 10 másodpercig.",
  "Húzd magadhoz hirtelen, és csókold meg mélyen.",
  "Csókolj végig a kulcscsontja másik oldalán is.",
  "Vezesd a kezét a csípődön körbe.",
  "Simíts végig a derekán lassan, két kézzel.",
  "Csókolj a nyakán, majd állj meg egy pillanatra.",
  "Érintsd meg a hátán az alsó részt finoman.",
  "Öleld magadhoz szorosan, és ne engedd 20 másodpercig.",
  "Táncoljatok közelebb, amíg teljesen összeértek.",
  "Csókolj végig lefelé a nyakától a mellkasáig ruhán keresztül.",
  "Húzd végig az ujjaid az ajkain, majd csókold meg.",
  "Súgd a fülébe, mit szeretnél vele tenni később."
],
    level2: [
  "Csókold végig lassan a nyakát, majd harapj bele finoman.",
  "Simíts végig a mellkasán két kézzel, lassan.",
  "Csókold meg a mellét érzékien, időzve rajta.",
  "Húzd közelebb a fenekénél fogva, és csókold meg mélyen.",
  "Csókold végig a kulcscsontjától lefelé.",
  "Térdelj elé, és csókold végig a hasát lassan.",
  "Simíts végig a belső combján, majd állj meg egy pillanatra.",
  "Csókold meg a mellét, majd térj vissza a nyakára.",
  "Húzd végig az ajkad a nyakától a válláig.",
  "Simíts végig a fenekén, majd szoríts rá finoman.",
  "Csókold végig a mellkasát lassú tempóban.",
  "Ülj az ölébe, és csókold meg szenvedélyesen.",
  "Csókolj végig lefelé a hasán, majd állj meg a köldökénél.",
  "Simíts végig a mellén, miközben a szemébe nézel.",
  "Fordítsd meg, és csókold végig a hátán a csípőjéig.",
  "Állva húzd magadhoz, és simíts végig a fenekén.",
  "Csókolj végig a nyakán, miközben a combját simogatod.",
  "Térdelj le, és közelíts érzékien a combjai között – még csak ígéretként.",
  "Engedd, hogy rövid, lassú figyelmet adjon neked térdelve vagy ülve.",
  "Csókold végig a mellét, majd lassan haladj lefelé.",
  "Simíts végig a derekán és a csípőjén két kézzel.",
  "Húzd magadhoz a fenekénél fogva, és éreztesd a vágyad.",
  "Csókolj végig a vállától a mellkasáig.",
  "Simíts végig a combjai belső oldalán, lassan felfelé.",
  "Ülj az ölébe háttal, és mozogj lassan rajta.",
  "Csókold végig a mellét tempóváltással.",
  "Húzd végig a kezed a hasán lefelé, majd nézz rá.",
  "Simíts végig a fenekén, miközben a nyakát csókolod.",
  "Térdelj közé, és adj rövid, érzéki figyelmet a combjai között.",
  "Engedd, hogy finoman irányítsa a fejed egy pillanatra.",
  "Állva csókold végig a mellkasát, miközben a csípőjét fogod.",
  "Simíts végig a mellén és a derekán egyszerre.",
  "Csókold végig a hátát lefelé, majd húzd közelebb.",
  "Húzd végig az ajkad a hasán, lassan.",
  "Adj neki rövid, lassú, vágyfokozó figyelmet térdelve.",
  "Engedd, hogy 30 másodpercig csak a száddal közelítsen hozzád.",
  "Simíts végig rajta tetőtől talpig, megállásokkal.",
  "Csókold végig a combját felfelé, majd állj meg mielőtt továbbmennél.",
  "Húzd közelebb a csípőjénél, és mozogjatok összeérve lassan.",
  "Fejezd be egy hosszú, mély csókkal, miközben a fenekét fogod."
],
    level3: [
  "Engedd, hogy 2 percig teljesen ő irányítson.",
  "Vedd át az irányítást, és határozd meg a tempót.",
  "Válts lassúból intenzívbe hirtelen.",
  "Tarts szemkontaktust legalább 30 másodpercig mozgás közben.",
  "Suttogd a fülébe, mennyire élvezed.",
  "Húzd közelebb a csípőjénél, és irányítsd a ritmust.",
  "Engedd, hogy a kezed a fenekén maradjon mozgás közben.",
  "Adj neki hosszabb, koncentrált figyelmet térdelve.",
  "Engedd, hogy ő térdeljen le, és lassan közeledjen.",
  "Válts tempót háromszor egymás után.",
  "Fogd meg a csuklóját finoman, miközben közeledsz.",
  "Tarts egy rövid szünetet a csúcspont előtt.",
  "Mozogj lassan, kontrolláltan 1 percig.",
  "Húzd közelebb magadhoz a combjánál.",
  "Engedd, hogy ő diktálja a ritmust egy teljes jelenetben.",
  "Adj neki intenzívebb figyelmet állva.",
  "Ülj rá, és irányítsd a tempót teljesen.",
  "Engedd, hogy ő üljön rád, és vezesse a mozgást.",
  "Válts dominánsabb energiára 1 percre.",
  "Majd válts gyengédebb, lassabb ritmusra.",
  "Térdelj közé, és adj neki hosszabb, elmélyült figyelmet.",
  "Engedd, hogy irányítsa a fejed egy rövid jelenetben.",
  "Fogd meg a fenekét határozottabban mozgás közben.",
  "Tartsd közel magadhoz a csípőjénél fogva.",
  "Mozogj lassan, mély tempóban legalább 1 percig.",
  "Állva húzd magadhoz, és vezesd a mozgást.",
  "Fektesd le, és irányítsd a ritmust teljesen.",
  "Engedd, hogy ő vezessen egy új tempót.",
  "Használj lassú, kontrollált mozdulatokat.",
  "Válts intenzívebb mozgásra egy jelzés után.",
  "Adj neki hosszabb, koncentrált orális figyelmet.",
  "Engedd, hogy ő viszonozza hosszabban.",
  "Válts ülőből fekvő helyzetbe, megszakítás nélkül.",
  "Fogd meg a csípőjét, és tartsd stabilan a tempót.",
  "Mozogjatok összehangolt ritmusban 1 percig.",
  "Húzd közelebb magadhoz domináns mozdulattal.",
  "Engedd, hogy ő tartson vissza egy pillanatra.",
  "Válts teljes kontrollról teljes átadásra.",
  "Használj mélyebb, lassabb tempót.",
  "Fejezd be a szintet egy intenzív, kontrollált jelenettel."
],
    level4: [
  "Adj lassú, kizárólag nyelves kényeztetést 1 percig.",
  "Most csak a kezedet használd, változó tempóban.",
  "Válts lassú orálisból intenzívebb ritmusra.",
  "Engedd, hogy ő irányítsa a tempót a kezével.",
  "Adj rövid, gyors ritmusú kényeztetést, majd lassíts.",
  "Térdelj elé, és tarts szemkontaktust közben.",
  "Engedd, hogy ő térdeljen le, és irányítsd finoman.",
  "Váltogasd a kéz és a száj használatát.",
  "Állva húzd magadhoz, és kezdj lassan közeledni.",
  "Ültesd le egy székre, és onnan irányítsd a ritmust.",
  "Helyezkedjetek el az ágy szélén, és váltogassátok a kontrollt.",
  "Próbáljatok ki egy falnak támasztott helyzetet.",
  "Ülj rá, és diktáld a tempót lassan.",
  "Engedd, hogy ő fordítson meg, és vegye át az irányítást.",
  "Válts pozíciót megszakítás nélkül.",
  "Most csak lassú, mély tempót használj.",
  "Most csak gyors, rövid mozdulatokkal dolgozz.",
  "Használj egyenletes ritmust 1 percig.",
  "Válts ritmust minden 10. mozdulat után.",
  "Tarts egy hosszabb szünetet, majd folytasd intenzíven.",
  "Fektesd le, és irányítsd a csípőjét a kezeddel.",
  "Engedd, hogy ő irányítsa a fejed mozdulatait.",
  "Térdelő pozícióban haladj lassan, kontrolláltan.",
  "Állva húzd fel a combját magadhoz.",
  "Próbáljatok ki egy oldalról kapcsolódó helyzetet.",
  "Most csak a nyelvedet használd, kéz nélkül.",
  "Most csak a kezed dolgozzon, lassan.",
  "Kombináld a két technikát tempóváltással.",
  "Engedd, hogy ő mondja meg, gyorsíts vagy lassíts.",
  "Adj intenzívebb, mélyebb figyelmet egy teljes percig.",
  "Fordítsd meg, és hátulról irányítsd a tempót.",
  "Ülj az ölébe, és lassan mozogj rajta.",
  "Fektesd az ágy szélére, és térdelj elé.",
  "Állva, falnál kapcsolódjatok össze rövid jelenetre.",
  "Válts fekvőből ülő pozícióba folyamatos mozgással.",
  "Most dominánsabban fogd meg a csípőjét.",
  "Engedd, hogy ő tartson vissza egy pillanatra.",
  "Tarts végig szemkontaktust intenzív ritmus mellett.",
  "Lassíts le teljes kontrollra 30 másodpercre.",
  "Fejezzétek be egy erős, mély tempójú jelenettel."
],
    level5: [
  "Addig ne álljatok meg, amíg az egyikőtök el nem jut a csúcsig.",
  "Tarts fenn lassú tempót, amíg ő könyörög a gyorsításért.",
  "Válassz egy pózt, amiben intenzíven tudod kontrollálni a ritmust.",
  "Engedd, hogy ő diktálja a tempót a csúcspontig.",
  "Tarts szemkontaktust, amíg az orgazmus közeledik.",
  "Vidd át a jelenetet a nappaliba, és ott folytassátok.",
  "Ültesd az asztal szélére, és onnan irányíts.",
  "Próbáljatok ki egy falnál történő intenzív jelenetet.",
  "Használjátok az ágy szélét stabil pozícióként.",
  "Feküdj le, és engedd, hogy ő üljön rád és vezesse a tempót.",
  "Játsszatok el egy „tiltott találkozás” szerepjátékot.",
  "Legyél domináns partner egy teljes jelenetben.",
  "Cseréljetek szerepet, és engedd, hogy ő irányítson keményebben.",
  "Válasszatok egy mély, intenzív pózt a csúcspont eléréséhez.",
  "Tarts rövid szünetet közvetlenül az orgazmus előtt.",
  "Engedd, hogy ő vezessen téged térdelő pozícióban.",
  "Adj intenzív, célzott figyelmet, amíg remegni kezd.",
  "Használj gyors tempót rövid ideig, majd mélyíts.",
  "Válts hátulról domináns pozícióra.",
  "Próbáljatok ki egy olyan pózt, ahol a combjai a válladon vannak.",
  "Húzd a hajánál finoman, miközben vezeted a tempót.",
  "Engedd, hogy ő irányítsa a fejed erősebben.",
  "Válassz egy pózt, ahol teljes kontrollod van a mozgás felett.",
  "Engedd, hogy ő tartson vissza egy pillanatra a csúcspont előtt.",
  "Mozogj intenzíven 1 percig megszakítás nélkül.",
  "Használjatok széket egy domináns ülő pozícióhoz.",
  "Fektesd az asztalra (biztonságosan), és onnan irányíts.",
  "Próbáljatok ki egy pózt a földön, teljes testkontaktussal.",
  "Vidd át a jelenetet a fürdőszobába.",
  "Kezdjétek a falnál, majd mozduljatok az ágyra.",
  "Adj hosszabb, intenzív orális jelenetet a csúcspontig.",
  "Engedd, hogy ő adjon neked intenzív, kontrollált orális figyelmet.",
  "Tarts mély, lassú tempót a csúcspont felépítéséhez.",
  "Válts gyors, erőteljes ritmusra az utolsó szakaszban.",
  "Engedd, hogy ő mondja ki, mikor közelít a csúcshoz.",
  "Játsszatok „nem mozdulhatsz” szabályt 30 másodpercig.",
  "Engedd, hogy ő teljesen uralja a mozgást egy jelenetben.",
  "Válts domináns hangnemre a végső szakaszban.",
  "Válasszatok egy merész pózt, amit ritkán használtok.",
  "Fejezzétek be egy intenzív, kontrollált orgazmus-jelenettel.",
  "Térdelj elé az ágy szélén, egyik kezeddel fogd a combját, a másikkal vezesd a ritmust – kezdj lassan, majd gyorsíts.",
  "Ültesd egy székre, állj elé, és adj lassú, mély figyelmet, miközben a csípőjénél tartod.",
  "Fektesd hátra a kanapén, térdelj közé, és váltogasd a tempót 30 másodpercenként.",
  "Engedd, hogy ő állva fogja a hajad, miközben te kontrollált, egyenletes ritmust tartasz.",
  "Csak a nyelvedet használd 1 percig, a kezed maradjon a combján vagy a csípőjén.",
  "Most csak a kezed dolgozzon, miközben a szemedbe néz – lassúból gyorsba váltva.",
  "Térdelj a földön az ágy mellett, egyik kezeddel a fenekét fogva, és haladj tempóváltással.",
  "Fektesd le, emeld meg kissé a csípőjét a kezeddel, és így adj intenzívebb figyelmet.",
  "Ülj a kanapéra, húzd közelebb magadhoz, és hagyd, hogy térdelve közeledjen hozzád, miközben a haját finoman vezeted.",
  "Válts tempót minden 15 másodpercben: lassú – gyors – mély – kontrollált, miközben a combját vagy a csípőjét tartod stabilan."
]
  }

};
